name: Flutter action
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: 3.19.0
          channel: stable

      - name: Flutter --version
        run: flutter --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Build AppBundle
        run: flutter build appbundle
