    - name: Flutter action
  # You may pin to the exact commit or the version.
  # uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56
  uses: subosito/flutter-action@v2.14.0
  with:
    # The Flutter version to make available on the path
    flutter-version: 3.19.0
    # The Flutter build release channel
    channel: 'main'
  steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.0
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
